export type PronunciationCategory =
  | "Java"
  | "Python"
  | "Vue"
  | "Frontend"
  | "Database"
  | "DevOps"
  | "General";

export type PronunciationTerm = {
  term: string;
  ipa: string;
  zhPronunciation: string;
  zhPurePronunciation: string;
  meaningZh: string;
  commonMistake: string;
  note: string;
  example: string;
  category: PronunciationCategory;
  speakText?: string;
};

export const pronunciationCategories = [
  "Java",
  "Python",
  "Vue",
  "Frontend",
  "Database",
  "DevOps",
  "General",
] as const satisfies readonly PronunciationCategory[];

export const pronunciationTerms = [
  {
    term: "Java",
    ipa: "/ˈdʒɑː.və/",
    zhPronunciation: "JAH-vuh / 扎-vuh",
    zhPurePronunciation: "抓哇",
    meaningZh: "Java 编程语言",
    commonMistake: "加瓦",
    note: "首音是 /dʒ/，不是中文拼音 j；第二个音节要轻。",
    example: "This service is written in Java.",
    category: "Java",
  },
  {
    term: "JVM",
    ipa: "/ˌdʒeɪ viː ˈem/",
    zhPronunciation: "J-V-M",
    zhPurePronunciation: "杰-威-艾姆",
    meaningZh: "Java 虚拟机",
    commonMistake: "按中文字母读",
    note: "按英文字母名逐个读，最后的 M 通常略重。",
    example: "The JVM handles memory management.",
    category: "Java",
  },
  {
    term: "JDK",
    ipa: "/ˌdʒeɪ diː ˈkeɪ/",
    zhPronunciation: "J-D-K",
    zhPurePronunciation: "杰-迪-凯",
    meaningZh: "Java 开发工具包",
    commonMistake: "按中文字母读",
    note: "三个字母都按英文名称读。",
    example: "Install the latest JDK before building the project.",
    category: "Java",
  },
  {
    term: "Spring",
    ipa: "/sprɪŋ/",
    zhPronunciation: "spring",
    zhPurePronunciation: "斯普润",
    meaningZh: "Spring 框架",
    commonMistake: "死不 ring",
    note: "开头是连续辅音 /spr/，中间不要加出中文的“死不”。",
    example: "Spring Boot starts the service quickly.",
    category: "Java",
  },
  {
    term: "Maven",
    ipa: "/ˈmeɪ.vən/",
    zhPronunciation: "MAY-vuhn",
    zhPurePronunciation: "梅文",
    meaningZh: "Java 构建工具",
    commonMistake: "马文",
    note: "第一音节是 /meɪ/，不是中文“马”。",
    example: "Maven downloads the dependency automatically.",
    category: "Java",
  },
  {
    term: "Gradle",
    ipa: "/ˈɡreɪ.dəl/",
    zhPronunciation: "GRAY-duhl",
    zhPurePronunciation: "格瑞豆",
    meaningZh: "构建工具",
    commonMistake: "格拉德",
    note: "重音在前，结尾是轻的 /dəl/。",
    example: "Gradle runs the build task.",
    category: "Java",
  },
  {
    term: "daemon",
    ipa: "/ˈdiː.mən/",
    zhPronunciation: "DEE-muhn",
    zhPurePronunciation: "滴门",
    meaningZh: "守护进程",
    commonMistake: "迪蒙、day-mon",
    note: "技术语境里常读作 /ˈdiː.mən/。",
    example: "The daemon keeps running in the background.",
    category: "Java",
  },
  {
    term: "enum",
    ipa: "/ˈiː.nəm/",
    zhPronunciation: "EE-nuhm",
    zhPurePronunciation: "衣能",
    meaningZh: "枚举",
    commonMistake: "e-num",
    note: "第一个音是长 /iː/，不是字母 E 加 num。",
    example: "Use an enum for fixed states.",
    category: "Java",
  },
  {
    term: "generic",
    ipa: "/dʒəˈner.ɪk/",
    zhPronunciation: "juh-NEH-rik",
    zhPurePronunciation: "哲奈瑞克",
    meaningZh: "泛型的",
    commonMistake: "gene-rik",
    note: "重音在第二音节。",
    example: "The generic type makes the API reusable.",
    category: "Java",
  },
  {
    term: "Hibernate",
    ipa: "/ˈhaɪ.bɚ.neɪt/",
    zhPronunciation: "HIGH-bur-nate",
    zhPurePronunciation: "嗨伯内特",
    meaningZh: "Hibernate ORM 框架",
    commonMistake: "hi-ber-nate",
    note: "开头像 high，重音在第一音节。",
    example: "Hibernate maps entities to database tables.",
    category: "Java",
  },
  {
    term: "deprecated",
    ipa: "/ˈdep.rə.keɪ.tɪd/",
    zhPronunciation: "DEP-ruh-kay-tid",
    zhPurePronunciation: "戴普若凯替德",
    meaningZh: "已废弃",
    commonMistake: "de-pre-ci-ated",
    note: "中间是 /rə/，不是 preci。",
    example: "This method is deprecated.",
    category: "Java",
  },
  {
    term: "synchronized",
    ipa: "/ˈsɪŋ.krə.naɪzd/",
    zhPronunciation: "SING-kruh-nized",
    zhPurePronunciation: "辛克若奈兹德",
    meaningZh: "同步的",
    commonMistake: "syn-chron-ized",
    note: "开头接近 sing，结尾是 nized。",
    example: "The synchronized block protects shared state.",
    category: "Java",
  },
  {
    term: "annotation",
    ipa: "/ˌæn.əˈteɪ.ʃən/",
    zhPronunciation: "an-uh-TAY-shuhn",
    zhPurePronunciation: "安呢忒深",
    meaningZh: "注解",
    commonMistake: "anno-ta-tion",
    note: "重音在 tay。",
    example: "The annotation marks this method as transactional.",
    category: "Java",
  },
  {
    term: "servlet",
    ipa: "/ˈsɝːv.lət/",
    zhPronunciation: "SURV-luht",
    zhPurePronunciation: "瑟夫勒特",
    meaningZh: "Servlet",
    commonMistake: "serve-let",
    note: "第二音节很轻。",
    example: "The servlet receives the request.",
    category: "Java",
  },
  {
    term: "repository",
    ipa: "/rɪˈpɑː.zə.tɔːr.i/",
    zhPronunciation: "ri-PAH-zuh-tory",
    zhPurePronunciation: "瑞帕泽托瑞",
    meaningZh: "仓库层、代码仓库",
    commonMistake: "repo-si-tory",
    note: "重音在第二音节。",
    example: "The repository hides database details.",
    category: "Java",
  },
  {
    term: "dependency",
    ipa: "/dɪˈpen.dən.si/",
    zhPronunciation: "di-PEN-duhn-see",
    zhPurePronunciation: "迪盆登西",
    meaningZh: "依赖",
    commonMistake: "de-pen-den-cy",
    note: "重音在 pen。",
    example: "Add the dependency to the build file.",
    category: "Java",
  },
  {
    term: "injection",
    ipa: "/ɪnˈdʒek.ʃən/",
    zhPronunciation: "in-JEK-shuhn",
    zhPurePronunciation: "因杰克深",
    meaningZh: "注入",
    commonMistake: "in-jek-tion",
    note: "后半段是 /ʃən/，不是 tion 逐字读。",
    example: "Dependency injection makes testing easier.",
    category: "Java",
  },
  {
    term: "transaction",
    ipa: "/trænˈzæk.ʃən/",
    zhPronunciation: "tran-ZAK-shuhn",
    zhPurePronunciation: "川扎克深",
    meaningZh: "事务",
    commonMistake: "trans-action",
    note: "重音在 zak，结尾是 /ʃən/。",
    example: "The transaction rolls back on failure.",
    category: "Java",
  },
  {
    term: "Python",
    ipa: "/ˈpaɪ.θɑːn/",
    zhPronunciation: "PIE-thon",
    zhPurePronunciation: "派森",
    meaningZh: "Python 编程语言",
    commonMistake: "派松",
    note: "中间是 /θ/ 咬舌音，不是 s。",
    example: "Python is great for backend scripts.",
    category: "Python",
  },
  {
    term: "Django",
    ipa: "/ˈdʒæŋ.ɡoʊ/",
    zhPronunciation: "JANG-go",
    zhPurePronunciation: "姜狗",
    meaningZh: "Django 框架",
    commonMistake: "di-jan-go",
    note: "D 不单独读，开头是 /dʒ/。",
    example: "Django includes an admin panel.",
    category: "Python",
  },
  {
    term: "FastAPI",
    ipa: "/fæst ˌeɪ piː ˈaɪ/",
    zhPronunciation: "fast A-P-I",
    zhPurePronunciation: "法斯特-诶-屁-艾",
    meaningZh: "FastAPI 框架",
    commonMistake: "fast-api 连成一个词乱读",
    note: "Fast 正常读，API 按字母名读。",
    example: "FastAPI generates OpenAPI docs.",
    category: "Python",
    speakText: "Fast A P I",
  },
  {
    term: "async",
    ipa: "/eɪˈsɪŋk/",
    zhPronunciation: "ay-SINK",
    zhPurePronunciation: "诶辛克",
    meaningZh: "异步",
    commonMistake: "啊-sync",
    note: "首音是 /eɪ/，重音在 sync。",
    example: "The async task is queued.",
    category: "Python",
  },
  {
    term: "await",
    ipa: "/əˈweɪt/",
    zhPronunciation: "uh-WAIT",
    zhPurePronunciation: "呃威特",
    meaningZh: "等待异步结果",
    commonMistake: "a-wait 重音错",
    note: "第一个音节很轻，重音在 wait。",
    example: "You need to await the database call.",
    category: "Python",
  },
  {
    term: "tuple",
    ipa: "/ˈtuː.pəl/",
    zhPronunciation: "TOO-puhl",
    zhPurePronunciation: "兔扑",
    meaningZh: "元组",
    commonMistake: "土普",
    note: "常见读法是 TOO-puhl；也有人读 TUH-puhl。",
    example: "The function returns a tuple.",
    category: "Python",
  },
  {
    term: "schema",
    ipa: "/ˈskiː.mə/",
    zhPronunciation: "斯 kee-muh",
    zhPurePronunciation: "斯ki么",
    meaningZh: "模式、结构定义",
    commonMistake: "斯基马、斯给马、斯切马",
    note: "`sch` 在这里读 /sk/，`ee` 是长 /iː/，不要写成中文“基”。",
    example: "The schema migration failed.",
    category: "Python",
  },
  {
    term: "decorator",
    ipa: "/ˈdek.ə.reɪ.t̬ɚ/",
    zhPronunciation: "DEK-uh-ray-ter",
    zhPurePronunciation: "戴克瑞特儿",
    meaningZh: "装饰器",
    commonMistake: "de-co-ra-tor",
    note: "重音在第一音节。",
    example: "The decorator wraps the route handler.",
    category: "Python",
  },
  {
    term: "generator",
    ipa: "/ˈdʒen.ə.reɪ.t̬ɚ/",
    zhPronunciation: "JEN-uh-ray-ter",
    zhPurePronunciation: "杰呢瑞特儿",
    meaningZh: "生成器",
    commonMistake: "gene-ra-tor",
    note: "开头是 jen，不是 gene。",
    example: "The generator yields one item at a time.",
    category: "Python",
  },
  {
    term: "virtualenv",
    ipa: "/ˈvɝː.tʃu.əl env/",
    zhPronunciation: "VUR-choo-uhl env",
    zhPurePronunciation: "沃丘欧-恩维",
    meaningZh: "虚拟环境",
    commonMistake: "virtual-env 每段都重读",
    note: "前半段按 virtual 读，env 可以读作 E-N-V 或 env。",
    example: "Create a virtualenv for this project.",
    category: "Python",
    speakText: "virtual env",
  },
  {
    term: "pip",
    ipa: "/pɪp/",
    zhPronunciation: "pip",
    zhPurePronunciation: "皮普",
    meaningZh: "Python 包工具",
    commonMistake: "P-I-P",
    note: "通常当作一个短词读，不逐字母读。",
    example: "Use pip to install the package.",
    category: "Python",
  },
  {
    term: "pytest",
    ipa: "/ˈpaɪ.test/",
    zhPronunciation: "PIE-test",
    zhPurePronunciation: "派测试",
    meaningZh: "Python 测试框架",
    commonMistake: "pee-test",
    note: "py 来自 Python，读 PIE。",
    example: "Run pytest before opening the pull request.",
    category: "Python",
  },
  {
    term: "coroutine",
    ipa: "/ˌkoʊ.ruːˈtiːn/",
    zhPronunciation: "koh-roo-TEEN",
    zhPurePronunciation: "扣如听",
    meaningZh: "协程",
    commonMistake: "co-ro-tine",
    note: "重音在 teen。",
    example: "A coroutine can pause and resume.",
    category: "Python",
  },
  {
    term: "iterable",
    ipa: "/ˈɪt̬.ɚ.ə.bəl/",
    zhPronunciation: "IT-er-uh-buhl",
    zhPurePronunciation: "伊特若波",
    meaningZh: "可迭代对象",
    commonMistake: "i-ter-able",
    note: "重音在第一音节。",
    example: "The function accepts any iterable.",
    category: "Python",
  },
  {
    term: "dictionary",
    ipa: "/ˈdɪk.ʃə.ner.i/",
    zhPronunciation: "DIK-shuh-ner-ee",
    zhPurePronunciation: "迪克神耐瑞",
    meaningZh: "字典",
    commonMistake: "dic-tion-ary",
    note: "中间是 /ʃə/，不是 tion 逐字读。",
    example: "A dictionary stores key-value pairs.",
    category: "Python",
  },
  {
    term: "attribute",
    ipa: "/ˈæt.rɪ.bjuːt/",
    zhPronunciation: "AT-ri-byoot",
    zhPurePronunciation: "艾吹比由特",
    meaningZh: "属性",
    commonMistake: "a-tri-bute",
    note: "作名词时重音通常在第一音节。",
    example: "The object has a name attribute.",
    category: "Python",
  },
  {
    term: "parameter",
    ipa: "/pəˈræm.ə.t̬ɚ/",
    zhPronunciation: "puh-RAM-uh-ter",
    zhPurePronunciation: "破然米特儿",
    meaningZh: "参数",
    commonMistake: "pa-ra-meter",
    note: "重音在 ram。",
    example: "The parameter is optional.",
    category: "Python",
  },
  {
    term: "argument",
    ipa: "/ˈɑːrɡ.jə.mənt/",
    zhPronunciation: "ARG-yuh-muhnt",
    zhPurePronunciation: "阿古门特",
    meaningZh: "实参",
    commonMistake: "ar-gu-ment",
    note: "重音在第一音节。",
    example: "Pass the argument by name.",
    category: "Python",
  },
  {
    term: "Vue",
    ipa: "/vjuː/",
    zhPronunciation: "view / viu",
    zhPurePronunciation: "维由",
    meaningZh: "Vue 前端框架",
    commonMistake: "V-U-E",
    note: "和 view 同音。",
    example: "We use Vue on the frontend.",
    category: "Vue",
    speakText: "view",
  },
  {
    term: "Vite",
    ipa: "/viːt/",
    zhPronunciation: "veet",
    zhPurePronunciation: "维特",
    meaningZh: "前端构建工具",
    commonMistake: "vite 像 bite",
    note: "官方读音接近 veet，不是 bite。",
    example: "Vite starts the dev server quickly.",
    category: "Frontend",
    speakText: "veet",
  },
  {
    term: "Nuxt",
    ipa: "/nʌkst/",
    zhPronunciation: "nukst",
    zhPurePronunciation: "纳克斯特",
    meaningZh: "Nuxt 框架",
    commonMistake: "next",
    note: "中间是 /ʌ/，结尾保留 kst。",
    example: "Nuxt adds routing conventions.",
    category: "Vue",
  },
  {
    term: "Pinia",
    ipa: "/ˈpiː.njə/",
    zhPronunciation: "PEE-nyuh",
    zhPurePronunciation: "屁呢呀",
    meaningZh: "Pinia 状态库",
    commonMistake: "pi-ni-a",
    note: "开头是长 /iː/，后半段轻。",
    example: "Pinia stores shared state.",
    category: "Vue",
  },
  {
    term: "props",
    ipa: "/prɑːps/",
    zhPronunciation: "props",
    zhPurePronunciation: "普若普斯",
    meaningZh: "组件属性",
    commonMistake: "pro-ps 分开读",
    note: "一个音节，开头 /pr/ 不要拆开。",
    example: "Pass the title through props.",
    category: "Vue",
  },
  {
    term: "emit",
    ipa: "/iˈmɪt/",
    zhPronunciation: "ee-MIT",
    zhPurePronunciation: "衣米特",
    meaningZh: "发出事件",
    commonMistake: "e-mit 重音错",
    note: "重音在 mit。",
    example: "The child component emits an event.",
    category: "Vue",
  },
  {
    term: "component",
    ipa: "/kəmˈpoʊ.nənt/",
    zhPronunciation: "kuhm-POH-nuhnt",
    zhPurePronunciation: "肯坡能特",
    meaningZh: "组件",
    commonMistake: "com-po-nent 每段重读",
    note: "第一个音节很轻，重音在 poh。",
    example: "Extract the button into a component.",
    category: "Frontend",
  },
  {
    term: "template",
    ipa: "/ˈtem.plət/",
    zhPronunciation: "TEM-pluht",
    zhPurePronunciation: "天普勒特",
    meaningZh: "模板",
    commonMistake: "tem-plate",
    note: "结尾不是 plate 的重读读法。",
    example: "The template contains the markup.",
    category: "Frontend",
  },
  {
    term: "reactive",
    ipa: "/riˈæk.tɪv/",
    zhPronunciation: "ree-AK-tiv",
    zhPurePronunciation: "瑞艾克替夫",
    meaningZh: "响应式的",
    commonMistake: "re-active 分开读",
    note: "重音在 ak。",
    example: "Vue tracks reactive state.",
    category: "Vue",
  },
  {
    term: "router",
    ipa: "/ˈruː.t̬ɚ/",
    zhPronunciation: "ROO-ter",
    zhPurePronunciation: "入特儿",
    meaningZh: "路由器、路由库",
    commonMistake: "rau-ter",
    note: "软件路由常读 ROO-ter；地区差异中也有人读 row-ter。",
    example: "The router maps paths to pages.",
    category: "Vue",
  },
  {
    term: "TypeScript",
    ipa: "/ˈtaɪp skrɪpt/",
    zhPronunciation: "TYPE-script",
    zhPurePronunciation: "泰普斯克瑞普特",
    meaningZh: "TypeScript",
    commonMistake: "type-s-cript",
    note: "type 和 script 两个词自然连读即可。",
    example: "TypeScript catches type errors early.",
    category: "Frontend",
  },
  {
    term: "JavaScript",
    ipa: "/ˈdʒɑː.və skrɪpt/",
    zhPronunciation: "JAH-vuh-script",
    zhPurePronunciation: "抓哇斯克瑞普特",
    meaningZh: "JavaScript",
    commonMistake: "加瓦-script",
    note: "Java 部分和 Java 语言同样读 JAH-vuh。",
    example: "JavaScript runs in the browser.",
    category: "Frontend",
  },
  {
    term: "framework",
    ipa: "/ˈfreɪm.wɝːk/",
    zhPronunciation: "FRAME-work",
    zhPurePronunciation: "弗瑞姆沃克",
    meaningZh: "框架",
    commonMistake: "fra-me-work",
    note: "frame 是一个音节，不拆成 fra-me。",
    example: "Choose the framework that fits the team.",
    category: "Frontend",
  },
  {
    term: "lifecycle",
    ipa: "/ˈlaɪfˌsaɪ.kəl/",
    zhPronunciation: "LIFE-cycle",
    zhPurePronunciation: "莱夫赛扣",
    meaningZh: "生命周期",
    commonMistake: "li-fe-cycle",
    note: "life 是一个完整音节。",
    example: "The lifecycle hook runs after mount.",
    category: "Frontend",
  },
  {
    term: "hydration",
    ipa: "/haɪˈdreɪ.ʃən/",
    zhPronunciation: "high-DRAY-shuhn",
    zhPurePronunciation: "嗨德瑞深",
    meaningZh: "水合",
    commonMistake: "hy-dra-tion",
    note: "重音在 dray，结尾是 /ʃən/。",
    example: "Hydration connects server HTML to client state.",
    category: "Frontend",
  },
  {
    term: "composable",
    ipa: "/kəmˈpoʊ.zə.bəl/",
    zhPronunciation: "kuhm-POH-zuh-buhl",
    zhPurePronunciation: "肯坡泽波",
    meaningZh: "可组合函数",
    commonMistake: "compose-able",
    note: "重音在 poh，后面轻读。",
    example: "Move this logic into a composable.",
    category: "Vue",
  },
  {
    term: "ref",
    ipa: "/ref/",
    zhPronunciation: "ref",
    zhPurePronunciation: "瑞夫",
    meaningZh: "Vue ref",
    commonMistake: "R-E-F",
    note: "在 Vue 里通常当一个短词读。",
    example: "Use ref for primitive reactive values.",
    category: "Vue",
  },
  {
    term: "slot",
    ipa: "/slɑːt/",
    zhPronunciation: "slot",
    zhPurePronunciation: "斯洛特",
    meaningZh: "插槽",
    commonMistake: "s-lot",
    note: "一个音节，不拆开。",
    example: "The slot renders custom content.",
    category: "Vue",
  },
  {
    term: "cache",
    ipa: "/kæʃ/",
    zhPronunciation: "凯什 / 开什",
    zhPurePronunciation: "凯什",
    meaningZh: "缓存",
    commonMistake: "卡切、卡其",
    note: "读起来接近英文 cash。",
    example: "I will update the cache layer.",
    category: "General",
  },
  {
    term: "queue",
    ipa: "/kjuː/",
    zhPronunciation: "Q / kiu",
    zhPurePronunciation: "Q",
    meaningZh: "队列",
    commonMistake: "奎尤、库额",
    note: "虽然有五个字母，但只读一个音节。",
    example: "The async task is queued.",
    category: "General",
  },
  {
    term: "suite",
    ipa: "/swiːt/",
    zhPronunciation: "sweet",
    zhPurePronunciation: "斯维特",
    meaningZh: "套件",
    commonMistake: "su-it",
    note: "和 sweet 同音。",
    example: "The test suite is slow.",
    category: "General",
  },
  {
    term: "issue",
    ipa: "/ˈɪʃ.uː/",
    zhPronunciation: "ISH-oo",
    zhPurePronunciation: "伊修",
    meaningZh: "问题、工单",
    commonMistake: "i-sue",
    note: "常见美式读法是 ISH-oo。",
    example: "Open an issue for this bug.",
    category: "General",
  },
  {
    term: "repo",
    ipa: "/ˈriː.poʊ/",
    zhPronunciation: "REE-poh",
    zhPurePronunciation: "瑞坡",
    meaningZh: "代码仓库",
    commonMistake: "re-po",
    note: "repository 的口语缩写，开头是长 /iː/。",
    example: "Clone the repo before editing.",
    category: "General",
  },
  {
    term: "deploy",
    ipa: "/dɪˈplɔɪ/",
    zhPronunciation: "di-PLOY",
    zhPurePronunciation: "迪普洛伊",
    meaningZh: "部署",
    commonMistake: "de-ploy",
    note: "重音在 ploy。",
    example: "Deploy the app after the build passes.",
    category: "General",
  },
  {
    term: "merge",
    ipa: "/mɝːdʒ/",
    zhPronunciation: "murj",
    zhPurePronunciation: "么之",
    meaningZh: "合并",
    commonMistake: "me-ge",
    note: "结尾是 /dʒ/，不是 ge。",
    example: "Merge the branch after review.",
    category: "General",
  },
  {
    term: "branch",
    ipa: "/bræntʃ/",
    zhPronunciation: "branch",
    zhPurePronunciation: "布兰吃",
    meaningZh: "分支",
    commonMistake: "b-ranch",
    note: "开头 /br/ 连在一起。",
    example: "Create a branch for the feature.",
    category: "General",
  },
  {
    term: "commit",
    ipa: "/kəˈmɪt/",
    zhPronunciation: "kuh-MIT",
    zhPurePronunciation: "肯米特",
    meaningZh: "提交",
    commonMistake: "co-mmit",
    note: "第一个音节很轻，重音在 mit。",
    example: "Commit the change with a clear message.",
    category: "General",
  },
  {
    term: "release",
    ipa: "/rɪˈliːs/",
    zhPronunciation: "ri-LEASE",
    zhPurePronunciation: "瑞利斯",
    meaningZh: "发布",
    commonMistake: "re-lease",
    note: "重音在 lease。",
    example: "The release includes bug fixes.",
    category: "General",
  },
  {
    term: "archive",
    ipa: "/ˈɑːr.kaɪv/",
    zhPronunciation: "AR-kive",
    zhPurePronunciation: "阿凯夫",
    meaningZh: "归档",
    commonMistake: "ar-chive",
    note: "ch 在这里读 /k/。",
    example: "Archive old logs every month.",
    category: "General",
  },
  {
    term: "module",
    ipa: "/ˈmɑː.dʒuːl/",
    zhPronunciation: "MAH-jool",
    zhPurePronunciation: "妈久",
    meaningZh: "模块",
    commonMistake: "mo-du-le",
    note: "美式常读 MAH-jool。",
    example: "Split the feature into a module.",
    category: "General",
  },
  {
    term: "package",
    ipa: "/ˈpæk.ɪdʒ/",
    zhPronunciation: "PAK-ij",
    zhPurePronunciation: "派克几",
    meaningZh: "包",
    commonMistake: "pa-cka-ge",
    note: "结尾是 /ɪdʒ/，不要按字母拆。",
    example: "The package exports a helper function.",
    category: "General",
  },
  {
    term: "API",
    ipa: "/ˌeɪ piː ˈaɪ/",
    zhPronunciation: "A-P-I",
    zhPurePronunciation: "诶-屁-艾",
    meaningZh: "接口",
    commonMistake: "api 当单词读",
    note: "按英文字母名读。",
    example: "The API returns JSON.",
    category: "General",
    speakText: "A P I",
  },
  {
    term: "CLI",
    ipa: "/ˌsiː el ˈaɪ/",
    zhPronunciation: "C-L-I",
    zhPurePronunciation: "西-艾欧-艾",
    meaningZh: "命令行界面",
    commonMistake: "cli 当单词读",
    note: "按英文字母名读。",
    example: "The CLI accepts a config file.",
    category: "General",
    speakText: "C L I",
  },
  {
    term: "GUI",
    ipa: "/ˌdʒiː juː ˈaɪ/",
    zhPronunciation: "G-U-I",
    zhPurePronunciation: "基-由-艾",
    meaningZh: "图形界面",
    commonMistake: "gui 当单词读",
    note: "常按英文字母名读。",
    example: "The GUI shows deployment status.",
    category: "General",
    speakText: "G U I",
  },
  {
    term: "bug",
    ipa: "/bʌɡ/",
    zhPronunciation: "bug",
    zhPurePronunciation: "巴格",
    meaningZh: "缺陷",
    commonMistake: "B-U-G",
    note: "一个短词，不逐字母读。",
    example: "This bug only happens in production.",
    category: "General",
  },
  {
    term: "feature",
    ipa: "/ˈfiː.tʃɚ/",
    zhPronunciation: "FEE-chur",
    zhPurePronunciation: "非吃儿",
    meaningZh: "功能",
    commonMistake: "fea-ture",
    note: "开头是长 /iː/。",
    example: "This feature needs more tests.",
    category: "General",
  },
  {
    term: "legacy",
    ipa: "/ˈleɡ.ə.si/",
    zhPronunciation: "LEG-uh-see",
    zhPurePronunciation: "来格西",
    meaningZh: "遗留的",
    commonMistake: "le-ga-cy",
    note: "重音在第一音节。",
    example: "The legacy service is hard to maintain.",
    category: "General",
  },
  {
    term: "refactor",
    ipa: "/ˌriːˈfæk.tɚ/",
    zhPronunciation: "ree-FAK-ter",
    zhPurePronunciation: "瑞发克特儿",
    meaningZh: "重构",
    commonMistake: "re-factor",
    note: "重音在 fak。",
    example: "Refactor this function after adding tests.",
    category: "General",
  },
  {
    term: "SQL",
    ipa: "/ˈsiː.kwəl/ or /ˌes kjuː ˈel/",
    zhPronunciation: "SEE-kwuhl / S-Q-L",
    zhPurePronunciation: "西阔 / 艾斯-Q-艾欧",
    meaningZh: "结构化查询语言",
    commonMistake: "只认一种读法",
    note: "sequel 和 S-Q-L 都常见，团队内统一即可。",
    example: "The SQL query needs an index.",
    category: "Database",
    speakText: "sequel",
  },
  {
    term: "Redis",
    ipa: "/ˈred.ɪs/",
    zhPronunciation: "RED-is",
    zhPurePronunciation: "瑞迪斯",
    meaningZh: "Redis 缓存数据库",
    commonMistake: "ree-dis",
    note: "开头是 red。",
    example: "Redis stores session data.",
    category: "Database",
  },
  {
    term: "Postgres",
    ipa: "/ˈpoʊst.ɡres/",
    zhPronunciation: "POST-gres",
    zhPurePronunciation: "破斯特格瑞斯",
    meaningZh: "PostgreSQL 简称",
    commonMistake: "post-grees",
    note: "结尾接近 gres。",
    example: "Postgres handles relational data.",
    category: "Database",
  },
  {
    term: "MySQL",
    ipa: "/ˌmaɪ ˌes kjuː ˈel/",
    zhPronunciation: "My-S-Q-L",
    zhPurePronunciation: "麦-艾斯-Q-艾欧",
    meaningZh: "MySQL 数据库",
    commonMistake: "my-sequel 固定化",
    note: "官方常读 My-S-Q-L。",
    example: "MySQL runs in a Docker container.",
    category: "Database",
    speakText: "My S Q L",
  },
  {
    term: "nginx",
    ipa: "/ˌen.dʒɪn ˈeks/",
    zhPronunciation: "engine-X",
    zhPurePronunciation: "恩津-艾克斯",
    meaningZh: "nginx 服务器",
    commonMistake: "en-ginks",
    note: "官方读法接近 engine X。",
    example: "nginx forwards traffic to the app.",
    category: "DevOps",
    speakText: "engine X",
  },
  {
    term: "Docker",
    ipa: "/ˈdɑː.kɚ/",
    zhPronunciation: "DAH-ker",
    zhPurePronunciation: "达克儿",
    meaningZh: "容器平台",
    commonMistake: "dock-er 重音错",
    note: "重音在第一音节。",
    example: "Docker builds the image.",
    category: "DevOps",
  },
  {
    term: "Kubernetes",
    ipa: "/ˌkuː.bɚˈnet̬.iːz/",
    zhPronunciation: "koo-ber-NET-eez",
    zhPurePronunciation: "库伯奈踢兹",
    meaningZh: "容器编排系统",
    commonMistake: "koo-ber-ne-tees",
    note: "重音在 net。",
    example: "Kubernetes schedules the pods.",
    category: "DevOps",
  },
  {
    term: "cron",
    ipa: "/krɑːn/",
    zhPronunciation: "cron",
    zhPurePronunciation: "克朗",
    meaningZh: "定时任务",
    commonMistake: "c-ron",
    note: "一个音节，开头 /kr/ 连读。",
    example: "The cron job runs every night.",
    category: "DevOps",
  },
  {
    term: "proxy",
    ipa: "/ˈprɑːk.si/",
    zhPronunciation: "PROK-see",
    zhPurePronunciation: "普若克西",
    meaningZh: "代理",
    commonMistake: "pro-xy",
    note: "x 发 /ks/。",
    example: "The proxy adds request headers.",
    category: "DevOps",
  },
  {
    term: "cluster",
    ipa: "/ˈklʌs.tɚ/",
    zhPronunciation: "KLUS-ter",
    zhPurePronunciation: "克拉斯特儿",
    meaningZh: "集群",
    commonMistake: "clu-ster",
    note: "开头 /kl/ 不要拆开。",
    example: "The cluster has three nodes.",
    category: "DevOps",
  },
  {
    term: "ingress",
    ipa: "/ˈɪn.ɡres/",
    zhPronunciation: "IN-gress",
    zhPurePronunciation: "因格瑞斯",
    meaningZh: "入口流量",
    commonMistake: "in-gress 重音错",
    note: "名词常重读第一音节。",
    example: "Ingress routes external traffic.",
    category: "DevOps",
  },
  {
    term: "latency",
    ipa: "/ˈleɪ.tən.si/",
    zhPronunciation: "LAY-tuhn-see",
    zhPurePronunciation: "雷吞西",
    meaningZh: "延迟",
    commonMistake: "la-ten-cy",
    note: "重音在 lay。",
    example: "High latency hurts user experience.",
    category: "DevOps",
  },
  {
    term: "throughput",
    ipa: "/ˈθruː.pʊt/",
    zhPronunciation: "THROO-put",
    zhPurePronunciation: "思如普特",
    meaningZh: "吞吐量",
    commonMistake: "through-put 分错、sroo-put",
    note: "开头是 /θr/，舌尖轻触牙齿。",
    example: "The queue improves throughput.",
    category: "DevOps",
  },
  {
    term: "observability",
    ipa: "/əbˌzɝː.vəˈbɪl.ə.t̬i/",
    zhPronunciation: "ub-zur-vuh-BIL-uh-tee",
    zhPurePronunciation: "呃布泽沃比利提",
    meaningZh: "可观测性",
    commonMistake: "observe-ability",
    note: "重音靠后，在 bil。",
    example: "Observability helps us debug production issues.",
    category: "DevOps",
  },
] as const satisfies readonly PronunciationTerm[];
